# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapThird Module' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'GoogleMaps'
pod 'GooglePlacePicker'
  pod 'GooglePlaces'

  # Pods for GoogleMapThird Module

  target 'GoogleMapThird ModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapThird ModuleUITests' do
    inherit! :search_paths
    # Pods for testing
  end
 end
