# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FbLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'

  # Pods for FbLogin

  target 'FbLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FbLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
